language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - sh unittest.sh
