language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python --version
  - pip install -U pip
  - pip install unittest
  - pip install --upgrade pip
  - pip install -r requirements.txt

install:
  - pip install -e .

script:
  - sh unittest.sh
